import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="bg-[#E7E7E3] p-5">
          <Header />
        </div>
        {children}
        <div className="bg-[#E7E7E3] ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
